Pyt 45 todo list solidity program
abhishekrapid/blockchain-learning pull request #1
Opened 2023-01-04 07:50 UTC by abhishekrapid

Please review the code.

2023-01-04 08:19 UTC, apoorv-nag requested changes

2023-01-04 08:19 UTC, apoorv-nag commented on src/contract/todolist.sol
> +contract TodoList {
Use openzeppelin Owner and ReentrancyGuard to secure the TodoList for particular owner who deploys the TodoList.

2023-01-04 08:19 UTC, apoorv-nag commented on src/contract/todolist.sol
> +    uint public nextTaskId;
instead of writing uint, write uint256 which tells about the exact datatype.

2023-01-04 08:19 UTC, apoorv-nag commented on src/contract/todolist.sol
> +}
create a function to get total_count of tasks

2023-01-04 11:24 UTC, abhishekrapid commented on src/contract/todolist.sol
> +    mapping(uint => string) private tasks;
Variable name changed.

2023-01-04 11:24 UTC, abhishekrapid commented on src/contract/todolist.sol
> +    uint public nextTaskId;
Datatype changed.

2023-01-04 11:25 UTC, abhishekrapid commented on src/contract/todolist.sol
> +    function removeTask(uint taskId) public {
Done.

2023-01-04 11:25 UTC, abhishekrapid commented on src/contract/todolist.sol
> +pragma solidity ^0.4.17;   // Specifies the version of solidity that our code is written with
Done.

2023-01-04 11:25 UTC, abhishekrapid commented on src/contract/todolist.sol
> +pragma solidity ^0.4.17;   // Specifies the version of solidity that our code is written with
Done

2023-01-05 06:11 UTC, abhishekrapid commented on src/contract/todolist.sol
> +contract TodoList {
Done.

2023-01-05 06:12 UTC, abhishekrapid commented on src/contract/todolist.sol
> +}
Done

2023-07-18 17:33 UTC, merged